from screens.mainWindow import MainWindow
from screens.gameModeSelectionWindow import GameModeSelectionWindow
from screens.gameWindow import GameWindow
from screens.gameScoreWindow import GameScoreWindow
from screens.scoreWindow import ScoreWindow
from screens.settingsWindow import SettingsWindow
from screens.loadingWindow import LoadingWindow